name: KLPlugin
main: com.d3t.klplugin.KLPlugin
version: 1.0.0
api-version: 1.16
softdepend: [Essehtials, Vault, ActionBarAPI, CrazyAdvancementsAPI]

permissions:
   klplugin.editimmoscores:
      description: Allows direct manipulation of Immo-Scores
      default: false 
   klplugin.bypassanticheat:
      description: Allows bypassing the anticheat mechanic
      default: false 
   klplugin.changedaylightgamerule:
      description: Allows changing the doDaylightCycle on the main world
      default: false 
   klplugin.temporaryop:
      description: Allows being a temporary operator by holding a command block in hand
      default: false 

commands:
   payscoreboardvalue:
      description: Pays a scoreboard value to a player [OBSOLETE].
      usage: /<payscoreboardvalue> [player] [scoreboard] [multiplier]
      permission: klplugin.payscore
   payimmoscores:
      description: Pays the ImmoPunkte revenue to all online players.
      usage: /<payscoreboardvalue> [player] [scoreboard] [multiplier]
      permission: klplugin.payscore
   listofflineplayers:
      description: Lists OfflinePlayers.
      usage: /<listofflineplayers>
      permission: klplugin.utility
   cmdblockop:
      description: Changes OP status of a player (Command blocks only).
      usage: /<cmdblockop> [player] [true|false]
      permission: klplugin.cmdblock
   cmdblockgamerule:
      description: Executes gamerule commands (Command blocks only).
      usage: /<cmdblockgamerule> [rule] [data] [pass]
      permission: klplugin.cmdblock
   giveimmopoints:
      description: Gives Immo-Points to the specified player.
      usage: /<giveimmopoints> [player] [immo-point-class] [amount]
      permission: klplugin.giveimmopoints
   tradeimmoep:
      description: Gives Extra Immo-Points to another player.
      usage: /<giveimmopoint> [player] [amount]
      permission: klplugin.immotrade
   calcimmodemand:
      description: Calculates demand rates for Immo-classes.
      usage: /<calcimmodemand>
      permission: klplugin.calcdemand
   immostatus:
      description: Shows demand and status of Immobilien
      usage: /<immostatus>
      permission: klplugin.immostatus
   modifyrate:
      description: Modifies a immo rate
      usage: /<modifyrate> [0-4] [0.5-2.0]
      permission: klplugin.immostatus
   pvpklasse:
      description: PVP Klassen selektor
      usage: /<pvpklasse> [0-2]
      permission: klplugin.pvpklasse
      default: true
   isworld:
      description: Checks if the executor is in the specified world
      usage: /<isworld> [name]
      permission: klplugin.internalcmds
   pvptick:
      description: Internal PVP game tick
      usage: /<pvptick>
      permission: klplugin.internalcmds
   applyloadouttoclass:
      description: Copies the contents of a chest into all players of the specified class.
      usage: /<applyloadouttoclass> [classID] [inventory X] [inventory Y] [inventory Z]
      permission: klplugin.internalcmds
   calcvelocity:
      description: Calculates velocities of all players
      usage: /<calcvelocity> [target-scoreboard] <multiplier>
      permission: klplugin.internalcmds
   stockinfo:
      description: Returns real life stock information
      usage: /<stockinfo> <symbol>
      permission: klplugin.stocks.info
   stocks:
      description: Shows your owned stocks
      usage: /<stocks>
      permission: klplugin.stocks.trade
   buystocks:
      description: Buy stocks from the stock market
      usage: /<buystocks> <symbol> <amount>
      permission: klplugin.stocks.trade
   sellstocks:
      description: Sells stocks at index (get indexes using /stocks)
      usage: /<sellstocks> <index>
      permission: klplugin.stocks.trade
